[mcp_servers.chrome-devtools]
args = ["chrome-devtools-mcp@latest"]
command = "npx"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
CONTEXT7_API_KEY = "ctx7sk-7baa880c-9bda-4619-a413-d480dbdbabb6"

[mcp_servers.playwright]
args = ["@playwright/mcp@latest"]
command = "npx"
